### ISSUE TITLE
Older versions to use with modpacks built on older versions of forge?

### ISSUE THREAD

**Issue by OverCxmplicated** [fr1kin/ForgeHax#254] opened 2020-10-07 17:26 UTC
Is there anywhere to find older versions of the 1.15.2 jar file for older forge versions? It keeps crashing when I'm not on the very latest version and the modpack I'm trying to use it with has mods that don't work at that forge version...
Where would I find an older version of this mod (looking for 31.2.36)

**Comment by fr1kin** [comment] 2020-10-07 18:08
Probably related to #235

**Comment by OverCxmplicated** [comment] 2020-10-07 19:33
So in theory forgehax should work for slightly older versions of forge?

**Comment by fr1kin** [comment] 2020-10-07 23:13
🤔 That would be weird. If the issue is what I think it is, it's a bug in the hack ForgeHax uses to load the mod file (1.13+ Forge does not allow coremods and mods to be in the same jar). Unlike the rest of the Forge API, FML is not really intended to be used for common modders; and so it is subject to changes that break functionality between versions.

**Comment by OverCxmplicated** [comment] 2020-10-08 14:56
Why do you bother with using a "hack" to load the coremod in the same file as the mod? Why not just make two files and have people just put two jar files in their mods folder?

**Comment by fr1kin** [comment] 2020-10-08 20:38
I'd rather avoid having two jars

**Comment by OverCxmplicated** [comment] 2020-10-08 23:02
Oh, also forgot to mention this in my last comment but it wasnt an issue with baritone

**Comment by fr1kin** [comment] 2020-12-09 22:29
Fixed in https://github.com/fr1kin/ForgeHax/commit/34d0342f65ad2f0c9e654185c013c1371fb0d87a

**Closed by fr1kin** 2020-12-09 22:29 UTC
Labels: duplicate
